# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: FABOAcademy X 2021 SPRING
description: Fablab O Shanghai “Fabo Academy X China”, is a digital manufacturing and rapid prototyping course based on MIT’s “How To Make (Almost) Anything” class (MAS.863/4.140/6.943) and Fab Foundation’s “Fab Academy” global. The course is an overview of the tools and practices commonly used in any Fablab, with a focus on design, project development and documentation. 
github_username: siyucchen

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
